### ISSUE TITLE
libvpx fails to build on aarch64

### ISSUE THREAD

**Issue by gtristan** [flatpak/freedesktop-sdk-base#13]
As shown in [this build log](https://gnome1.codethink.co.uk//logs/build-2018-01-07-104001/build-freedesktop-sdk-base-1-6-aarch64.txt)

It appears that `armv8-linux-gcc` is a valid toolchain for recent libvpx, according to [this README](https://chromium.googlesource.com/webm/libvpx/+/master/README), however it looks like we are building 1.5.0 but the latest is 1.6.1, seeing as 1.5.0 is over 2 years old, it's most likely that it did not have support for aarch64.

**Comment by alexlarsson** [comment]
I pushed a fix for this:
https://github.com/flatpak/freedesktop-sdk-base/commit/816e6c7a20e7358c42c16ffa6e9589dd652c344a#diff-88665837114dcf9f5ca6f36305fd2611
