### ISSUE TITLE
cmake lib64

### ISSUE THREAD

**Issue by eszlari** [flatpak/freedesktop-sdk-base#15]
After commit https://github.com/flatpak/freedesktop-sdk-base/commit/6adb6f49e52575956cf6aa0bbd3a1d8054735a43 I did https://github.com/flathub/org.kde.krita/commit/70d55bde1f7819e27e74b52462f59d588f1d4f3a but libs are now placed under /lib64 again. Am I missing something?

**Comment by alexlarsson** [comment]
Can you verify that the sdk you're using has that change? Maybe we need to rebuild the kde sdk against the new freedesktop sdk?

**Comment by eszlari** [comment]
You were right, it seems like the KDE SDK was not updated @aleixpol

**Comment by alexlarsson** [comment]
I can trigger a rebuild of it

**Comment by alexlarsson** [comment]
Building here: https://flathub.org/builds/#/builders/1/builds/1968

**Comment by aleixpol** [comment]
Weird... thanks

**Comment by alexlarsson** [comment]
Should be ok now

**Comment by eszlari** [comment]
@alexlarsson While now certain projects install under /lib (e.g. OpenCV, exiv2), everything from KDE (krita, kdenlive, kfilemetadata) still installs under /lib64.

**Comment by alexlarsson** [comment]
Honestly, my cmake knowledge is reaching its limits here...

**Comment by aleixpol** [comment]
@eszlari are you sure about that? it seems to work fine on my system.

**Comment by eszlari** [comment]
@aleixpol Just install `org.kde.krita` from flathub and see it yourself!

Maybe `KDE_INSTALL_LIBDIR` needs to be set?
https://api.kde.org/ecm/kde-module/KDEInstallDirs.html

**Comment by aleixpol** [comment]
Just did, still looks like Krita. Please be more specific.

**Comment by eszlari** [comment]
In commit https://github.com/flathub/org.kde.krita/commit/0bdb6ba1205489c84dbb5e4252e408fa544a437d I dropped `CMAKE_INSTALL_LIBDIR=lib` from the krita module. Now if you look at `/var/lib/flatpak/app/org.kde.krita/current/active/files`, you will see that there is a `lib64` directory.
