### ISSUE TITLE
cmake projects that use ECM still default to /lib64

### ISSUE THREAD

**Issue by eszlari** [flatpak/freedesktop-sdk-base#22]
Installing to /lib64 is supposed to be fixed: https://github.com/flatpak/freedesktop-sdk-base/commit/6adb6f49e52575956cf6aa0bbd3a1d8054735a43

But cmake based projects that use ECM (extra-cmake-modules) still install in /lib64 when not using `-DCMAKE_INSTALL_LIBDIR=lib`.

**Comment by eszlari** [comment]
Maybe @aleixpol @grulja have an idea.

**Comment by eszlari** [comment]
A similar fix that was applied to `GNUInstallDirs` (https://github.com/flatpak/freedesktop-sdk-base/commit/6adb6f49e52575956cf6aa0bbd3a1d8054735a43) needs to be applied to `KDEInstallDirs`:

https://github.com/KDE/extra-cmake-modules/blob/master/kde-modules/KDEInstallDirs.cmake

@alexlarsson @aleixpol @grulja The question is: Should this be fixed upstream or should a patch be added to` org.kde.Sdk`, like it is the case with `GNUInstallDirs`?

**Comment by aleixpol** [comment]
https://phabricator.kde.org/D13102
