### ISSUE TITLE
Still generating in lib64 when a cmake project is used via meson

### ISSUE THREAD

**Issue by KaruroChori** [flatpak/freedesktop-sdk-base#29]
Referencing https://github.com/flatpak/freedesktop-sdk-base/issues/22, this issue is still present when cmake is used in a meson subproject as part of a flatpak-builder run.

**Comment by TingPing** [comment]
This is a dead repository. The SDK is here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk
